apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: trevorblades
spec:
  name: trevorblades-subgraph
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: https://countries.trevorblades.com
    listen_path: /trevorblades
    strip_listen_path: true
  internal: true
  graphql:
    schema: |
      directive @key(fields: _FieldSet!) on OBJECT | INTERFACE

      directive @extends on OBJECT

      directive @external on FIELD_DEFINITION

      directive @requires(fields: _FieldSet!) on FIELD_DEFINITION

      directive @provides(fields: _FieldSet!) on FIELD_DEFINITION

      scalar _Any

      union _Entity = Product | User

      scalar _FieldSet

      type _Service {
        sdl: String
      }

      type Entity {
        findProductByUpc(upc: String!): Product!
        findUserByID(id: ID!): User!
      }

      type Product {
        upc: String!
        reviews: [Review]
      }

      type Query {
        _entities(representations: [_Any!]!): [_Entity]!
        _service: _Service!
      }

      type Review {
        body: String!
        author: User!
        product: Product!
      }

      type User {
        id: ID!
        username: String!
        reviews: [Review]
      }
    enabled: true
    engine:
      field_configs: []
      data_sources: []
    type_field_configurations: []
    execution_mode: subgraph
    proxy:
      auth_headers: {}
    subgraph:
      sdl: |
        type Review {
            body: String!
            author: User! @provides(fields: "username")
            product: Product!
        }

        extend type User @key(fields: "id") {
            id: ID! @external
            username: String! @external
            reviews: [Review]
        }

        extend type Product @key(fields: "upc") {
            upc: String! @external
            reviews: [Review]
        }
    supergraph:
      subgraphs:
        - api_id: ''
          name: ''
          url: ''
          sdl: ''
      merged_sdl: ''
      global_headers: {}
    version: '2'
    playground:
      enabled: false
      path: ''
    last_schema_update: '2022-03-09T14:30:52.698+01:00'
