# permissions for end users to view portalapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portalapi-viewer-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapis/status
  verbs:
  - get
