# permissions for end users to edit portalapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portalapi-editor-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapis/status
  verbs:
  - get
