
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - backendpolicies
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - backendpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.x-k8s.io
  resources:
  - gatewayclasses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - gatewayclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.x-k8s.io
  resources:
  - gateways
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.x-k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - httproutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.x-k8s.io
  resources:
  - tcproutes
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - tcproutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.x-k8s.io
  resources:
  - tlsroutes
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - tlsroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.x-k8s.io
  resources:
  - udproutes
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - udproutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidefinitions
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidescriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidescriptions/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidescriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - operatorcontexts
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapicatalogues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapicatalogues/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapicatalogues/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tyk.tyk.io
  resources:
  - securitypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - securitypolicies/status
  verbs:
  - get
  - patch
  - update
