name: Tyk Pro Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
  - cron: "*/5 * * * *"

jobs:
  matrix-generator:
    runs-on: ubuntu-latest
    steps:
        - name: Setup matrix combinations
          id: setup-matrix-combinations-schedule
          if: ${{ github.event_name }} == "schedule"
          run: |
            MATRIX_PARAMS_COMBINATIONS='
                {"k8s": "kindest/node:v1.18.0"},
                {"k8s": "kindest/node:v1.22.0"},
                {"k8s": "kindest/node:v1.23.0"},
            '
            echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
        - name: Setup matrix combinations pr
          id: setup-matrix-combinations-pr
          if: ${{ github.event_name }} == "pull_request" || ${{ github.event_name }} == "push"
          run: |
            MATRIX_PARAMS_COMBINATIONS='
                {"k8s": "kindest/node:v1.18.0"},
                {"k8s": "kindest/node:v1.19.0"},
            '
            echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
        - name: Decide which variable
          id: decider
          run: |
            if [ $REF != ""]
            then 
              echo "got 1st if"
              echo "${{steps.setup-matrix-combinations-schedule.outputs.matrix-combinations}}"
#              echo "::set-output name=matrix-combinations::'${{steps.setup-matrix-combinations-schedule.outputs.matrix-combinations}}'"
              echo "json_body=${{steps.setup-matrix-combinations-schedule.outputs.matrix-combinations}}" >> $GITHUB_ENV
            else
              echo "got else"
              echo "${{steps.setup-matrix-combinations-pr.outputs.matrix-combinations}}"
#              echo "::set-output name=matrix-combinations::'${{steps.setup-matrix-combinations-pr.outputs.matrix-combinations}}'"
              echo "json_body=${{steps.setup-matrix-combinations-pr.outputs.matrix-combinations}}" >> $GITHUB_ENV
                 
           fi
          env:
            REF: ${{ steps.setup-matrix-combinations-schedule.outputs.matrix-combinations }}
    outputs:
      matrix-combinations: ${{ steps.decider.outputs.matrix-combinations }}

  pro-tests:
    runs-on: ubuntu-20.04
    needs: matrix-generator
    strategy:
      matrix: ${{ fromJson(env.json_body) }}
    steps:
      - name: checkout tyk-operator
        uses: actions/checkout@v2
      - name: create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          wait: 2m
          node_image: ${{ matrix.k8s }}
          config: hack/kind.yaml
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: bootstrap tyk pro env
        shell: bash
        env:
          TYK_DB_LICENSEKEY: ${{ secrets.DASH_LICENSE }}
        run: |
          make boot-pro IMG=tykio/tyk-operator:test CLUSTER_NAME=chart-testing
      - name: bdd
        shell: bash
        run: |
          TYK_MODE=pro CLUSTER_NAME=chart-testing  make test-all
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
